character_2:UseSkill(2)
character_1:OnPartyMembers2(2, 5):UseSkill(4)
Wait(500)
character_1:UseSkill(1)
character_1:UseSkill(2)
character_1:UseSkill(3)
character_2:UseSkill(2)
character_3:UseSkill(3)
Summon(1)
EnableChargeAttack()